export const mockReservationData = {
  reservationId: 48,
  studioId: 1,
  studioName: '아워유스',
  startTime: '16:30:00',
  endTime: '17:00:00',
  menuId: 1,
  menuName: '증명사진',
  additionalMenuIds: [],
  additionalMenuNames: [],
  additionalMenuPrices: [],
  userName: '터치즈',
  userPhone: '01012345678',
  note: '',
  totalPrice: 78000,
  status: 'WAITING',
  date: '2025-07-01',
  basicPrice: 78000,
  paymentMethod: '카카오페이',
  menuImageUrl: 'https://i.imgur.com/ItWR5sD.jpeg',
  cancelReason: null,
  cancelReasonDetail: null,
  cancelDateTime: null,
};
